name: Release

on:
  push:
    branches:
      - main  # Ou votre branche principale

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release  # Utilisez l'environnement si nécessaire

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.1  # Version de Node.js nécessaire pour Semantic Release

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: npx semantic-release
